version: '3'
services:
  web:
    image: e8learncourseonline
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb+srv://hotrongson:hotrongson@cluster0.rqpoogd.mongodb.net/?retryWrites=true&w=majority
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  mongodb:
    image: mongo
    volumes:
      - ./data:/data/db
