version: '3'
services:
  app:
    image: e8learncourseonline
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb+srv://hotrongson:hotrongson@cluster0.rqpoogd.mongodb.net/?retryWrites=true&w=majority
    depends_on:
      - mongodb
    volumes:
      - ./:/var/www/app:cached
      - /var/www/app/node_modules
    restart: always
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
